# vim: set filetype=dockefile  foldlevel=0: vim modeline( set )

FROM ubuntu:18.04

ADD sources.list /etc/apt/sources.list

RUN \
    apt-get update  && \
    apt-get install -y less && \
    apt-get install -y file && \
    apt-get install -y net-tools      && \
    apt-get install -y netcat-openbsd && \
    apt-get install -y iproute2 && \
    apt-get install -y iputils-ping

