# vim: set filetype=dockerfile  foldlevel=0: vim modeline( set )

# FROM ubuntu

# FROM ubuntu:16.04
# ADD ubuntu-16-xential.list    /etc/apt/sources.list

FROM ubuntu:18.04
ADD ubuntu-18-bionic.list    /etc/apt/sources.list


RUN \
  apt-get update && \
  apt-get install -y netcat-openbsd && \
  apt-get install -y file           && \
  apt-get install -y iproute2       && \
  apt-get install -y iputils-ping   && \
  apt-get install -y bridge-utils   && \
  apt-get install -y tcpdump        && \
  apt-get install -y dsniff         && \
  apt-get install -y net-tools


RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump


CMD ["nc", "-l", "-p", "9200", "-k"]
